### ISSUE TITLE
Отступы неправильные

### ISSUE THREAD

**Issue by denver411** [MiMisar/HomeWork7#3]
https://github.com/MiMisar/HomeWork7/blob/c8040291ec7e20376113870779cd37fa846cc46e/index.html#L91

Между элементами должно быть по 30 px, а у тебя по 60. Плюс у крайних элементов не должно быть отступов (у первого слева, у последнего справа). То же самое замечание по второму блоку навигации
И если удалить один блок, оставив 3 элемента, то отступы слетают, а по условиям должно работать с любым количеством элементов

**Comment by MiMisar** [comment]
Проверь, вроде исправил.
